<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<title>PT SUNI FATHI INDONESIA </title>';
echo '<meta content="width=device-width, initial-scale=1.0" name="viewport">';
echo '<meta content="" name="keywords">';
echo '<meta content="" name="description">';
echo '';
echo '<!-- Favicon -->';
echo '<link href="img/favicon.ico" rel="icon">';
echo '';
echo '<!-- Google Web Fonts -->';
echo '<link rel="preconnect" href="https://fonts.googleapis.com">';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
echo '<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">';
echo '';
echo '<!-- Icon Font Stylesheet -->';
echo '<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">';
echo '';
echo '<!-- Libraries Stylesheet -->';
echo '<link href="lib/animate/animate.min.css" rel="stylesheet">';
echo '<link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">';
echo '';
echo '<!-- Customized Bootstrap Stylesheet -->';
echo '<link href="css/bootstrap.min.css" rel="stylesheet">';
echo '<link rel="stylesheet" href="css/language.css">';
echo '<!-- Template Stylesheet -->';
echo '<link href="css/style.css" rel="stylesheet">';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="container-xxl bg-white p-0">';
echo '<!-- Spinner Start -->';
echo '<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">';
echo '<div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">';
echo '<span class="sr-only">Loading...</span>';
echo '</div>';
echo '</div>';
echo '<!-- Spinner End -->';
echo '';
echo '';
echo '<!-- Navbar Start -->';
echo '<div class="container-fluid nav-bar bg-transparent">';
echo '<nav class="navbar  navbar-expand-lg bg-white navbar-light py-0 px-4" >';
echo '<a href="index.php" class="navbar-brand d-flex align-items-center text-center">';
echo '<div class="logo-container">';
echo '<img class="img-fluid" src="img/logo/sfi logo.png" alt="Icon">';
echo '</div>';
echo '</a>';
echo '<button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarCollapse">';
echo '<div class="navbar-nav ms-auto">';
echo '<a href="index.php" class="nav-item nav-link active">Home</a>';
echo '<a href="about.php" class="nav-item nav-link">About us</a>';
echo '<a href="products.php" class="nav-item nav-link">Products</a>';
echo '';
echo '<a href="contact.php" class="nav-item nav-link">Contact us</a>';
echo '</div>';
echo '<div class="trans-section">';
echo '<div id="google_translate_element"></div>';
echo '';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '</div>';
echo '<!-- Navbar End -->';
echo '';
echo '';
echo '<!-- Header Start -->';
echo '<div class="container-fluid header bg-white p-0">';
echo '<div class="row g-0 align-items-center flex-column-reverse flex-md-row">';
echo '<div class="col-md-6 p-5 mt-lg-5">';
echo '<h1 class="display-5 animated fadeIn mb-4">About Us</h1>';
echo '<nav aria-label="breadcrumb animated fadeIn">';
echo '<ol class="breadcrumb text-uppercase">';
echo '<li class="breadcrumb-item"><a href="index.php">Home</a></li>';
echo '';
echo '<li class="breadcrumb-item text-body active" aria-current="page">About</li>';
echo '</ol>';
echo '</nav>';
echo '</div>';
echo '<div class="col-md-6 animated fadeIn">';
echo '<img class="img-fluid" src="img/header/top-view-fishes-with-fishing-net.jpg" alt="">';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '<!-- Header End -->';
echo '';
echo '';
echo '<!-- Search Start -->';
echo '<div class="container-fluid bg-primary mb-5 wow fadeIn mt-4" data-wow-delay="0.1s" style="padding: 35px;">';
echo '<div class="container">';
echo '<div class="row g-2">';
echo '<div class="col-md-10">';
echo '<div class="row g-2">';
echo '<div class="col-md-4">';
echo '<div class="card border-0 h-100">';
echo '<div class="card-body">';
echo '<i class="fas fa-medal"></i> Premium Quality Seafood';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4">';
echo '<div class="card border-0 h-100">';
echo '<div class="card-body">';
echo '<i class="fas fa-leaf"></i> Sustainable Sourcing Practices';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4">';
echo '<div class="card border-0 h-100">';
echo '<div class="card-body">';
echo '<i class="fas fa-truck"></i> Reliable and Efficient Delivery';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-md-2">';
echo '<button class="btn btn-dark border-0 w-100 py-3">EXPLORE</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Search End -->';
echo '';
echo '';
echo '<!-- About Start -->';
echo '<div class="container-xxl py-5">';
echo '<div class="container">';
echo '<div class="row g-5 align-items-center">';
echo '<div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">';
echo '<div class="about-img position-relative overflow-hidden p-5 pe-0">';
echo '<img class="img-fluid w-100" src="img/about/top-view-mix-fresh-fishes-ice.jpg">';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">';
echo '<h1 class="mb-4">About us</h1>';
echo '<h3 class="mb-4">#1 Trusted Frozen fish Source, Fresh & Sustainable</h3>';
echo '<p class="mb-4">Welcome to SFI (PT SUNI FATHI INDONESIA), your premier international fish trading company basedinIndonesia. We take immense pride in sourcing, processing, and distributing the finest <span style="color: rgb(53, 53, 53); font-weight: 500;">Sea frozen fish</span> and seafood products to customers worldwide. With our extensive experience and';
echo 'unwavering commitment to quality, we have established ourselves as a trusted name in the global';
echo 'sea frozen fish and seafood products industry.</p>';
echo '<p>At SFI, we understand the importance of delivering exceptional Frozen fish (sea and land) and seafoodproducts that meet the highest standards. We work closely with local fishermen, fish farms, and';
echo 'processing facilities to ensure that our Frozen fish (sea and land) and seafood products is sourcedsustainably and processed with the utmost care. Our rigorous quality control measures guarantee that';
echo 'every product that leaves our facilities is of the finest quality, freshness, and taste.';
echo '';
echo '</p>';
echo '<p>';
echo 'Our product range is diverse, offering a wide selection of fish and Frozen fish to cater to the uniquepreferences of our customers. From popular species like Tuna, yellowfin tuna, Red snapper, barakuda,groupers,';
echo 'kingfish , catfish , black pomfret,  shrimp and squid etc, we strive to provide a comprehensive range that satisfies the demands of restaurants, sea frozen fish and seafood products distributors, and retailers worldwide.';
echo '';
echo '</p>';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container-xxl py-5">';
echo '<div class="container">';
echo '<div class="row g-5 align-items-center">';
echo '<div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">';
echo '';
echo '<p class="mb-4"> We take great pride in our commitment to sustainability. As stewards of the ocean, we recognize theimportance of responsible fishing practices to protect marine ecosystems for future generations. By';
echo 'adhering to sustainable fishing methods, supporting local communities, and engaging in initiatives that';
echo 'promote conservation, we ensure that our operations have a minimal environmental impact.';
echo '</p>';
echo '<p>At SFI, we value our relationships with our customers and prioritize their satisfaction above all else.';
echo 'Weunderstand the importance of reliability, efficiency, and timely delivery. With our robust logistics networkand';
echo 'partnerships with reputable shipping';
echo 'and freight companies, we ensure that your orders are handledwith the utmost care and reach your destination on schedule.</p>';
echo '<p>Our dedicated team of professionals is always ready to assist you. We are committed to providing';
echo 'personalized service, addressing your inquiries, and assisting you in finding the perfect sea frozen fish and seafood products solutions for your specific needs. Our expertise, coupled with our';
echo 'passion for excellence, makes us your ideal partner in the international sea frozen fish andseafood products trade.</p>';
echo '<p>Thank you for visiting our website and considering SFI as your trusted sea frozen fish andseafood products supplier. We invite you to explore our wide range of products, learn more about our';
echo 'sustainable practices, and get in touch with us for any inquiries or business opportunities. We look';
echo 'forward to serving you with the finest sea frozen fish and seafood products fromIndonesia.';
echo '</p>';
echo '';
echo '</div>';
echo '<div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">';
echo '<div class="about-img2 position-relative overflow-hidden p-5 pe-0">';
echo '<img class="img-fluid w-100" src="img/about/20230612164953_[fpdl.in]_top-view-variety-fresh-fish-seafood-ice_126277-745_normal.jpg">';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- About End -->';
echo '';
echo '';
echo '<!-- Call to Action Start -->';
echo '<!-- <div class="container-xxl py-5">';
echo '<div class="container">';
echo '<div class="bg-light rounded p-3">';
echo '<div class="bg-white rounded p-4" style="border: 1px dashed rgba(0, 185, 142, .3)">';
echo '<div class="row g-5 align-items-center">';
echo '<div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">';
echo '<img class="img-fluid rounded w-100" src="img/call-to-action.jpg" alt="">';
echo '</div>';
echo '<div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">';
echo '<div class="mb-4">';
echo '<h1 class="mb-3">Contact With Our Certified Agent</h1>';
echo '<p>Eirmod sed ipsum dolor sit rebum magna erat. Tempor lorem kasd vero ipsum sit sit diam justo sed vero dolor duo.</p>';
echo '</div>';
echo '<a href="" class="btn btn-primary py-3 px-4 me-2"><i class="fa fa-phone-alt me-2"></i>Make A Call</a>';
echo '<a href="" class="btn btn-dark py-3 px-4"><i class="fa fa-calendar-alt me-2"></i>Get Appoinment</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div> -->';
echo '<!-- Call to Action End -->';
echo '';
echo '';
echo '<!-- Team Start -->';
echo '<!-- <div class="container-xxl py-5">';
echo '<div class="container">';
echo '<div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">';
echo '<h1 class="mb-3">Property Agents</h1>';
echo '<p>Eirmod sed ipsum dolor sit rebum labore magna erat. Tempor ut dolore lorem kasd vero ipsum sit eirmod sit. Ipsum diam justo sed rebum vero dolor duo.</p>';
echo '</div>';
echo '<div class="row g-4">';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="team-item rounded overflow-hidden">';
echo '<div class="position-relative">';
echo '<img class="img-fluid" src="img/team-1.jpg" alt="">';
echo '<div class="position-absolute start-50 top-100 translate-middle d-flex align-items-center">';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-facebook-f"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-instagram"></i></a>';
echo '</div>';
echo '</div>';
echo '<div class="text-center p-4 mt-3">';
echo '<h5 class="fw-bold mb-0">Full Name</h5>';
echo '<small>Designation</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.3s">';
echo '<div class="team-item rounded overflow-hidden">';
echo '<div class="position-relative">';
echo '<img class="img-fluid" src="img/team-2.jpg" alt="">';
echo '<div class="position-absolute start-50 top-100 translate-middle d-flex align-items-center">';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-facebook-f"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-instagram"></i></a>';
echo '</div>';
echo '</div>';
echo '<div class="text-center p-4 mt-3">';
echo '<h5 class="fw-bold mb-0">Full Name</h5>';
echo '<small>Designation</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.5s">';
echo '<div class="team-item rounded overflow-hidden">';
echo '<div class="position-relative">';
echo '<img class="img-fluid" src="img/team-3.jpg" alt="">';
echo '<div class="position-absolute start-50 top-100 translate-middle d-flex align-items-center">';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-facebook-f"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-instagram"></i></a>';
echo '</div>';
echo '</div>';
echo '<div class="text-center p-4 mt-3">';
echo '<h5 class="fw-bold mb-0">Full Name</h5>';
echo '<small>Designation</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.7s">';
echo '<div class="team-item rounded overflow-hidden">';
echo '<div class="position-relative">';
echo '<img class="img-fluid" src="img/team-4.jpg" alt="">';
echo '<div class="position-absolute start-50 top-100 translate-middle d-flex align-items-center">';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-facebook-f"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-instagram"></i></a>';
echo '</div>';
echo '</div>';
echo '<div class="text-center p-4 mt-3">';
echo '<h5 class="fw-bold mb-0">Full Name</h5>';
echo '<small>Designation</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div> -->';
echo '<!-- Team End -->';
echo '';
echo '';
echo '<!-- Footer Start -->';
echo '<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">';
echo '<div class="container py-5">';
echo '<div class="row g-5">';
echo '<div class="col-lg-3 col-md-6 ">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid " src="img/logo/sfi logo.png" alt="Icon">';
echo '</div>';
echo '<div class="d-flex" style="padding-left: 60px;">';
echo '';
echo '<a class="btn btn-outline-light btn-social" href="https://www.instagram.com/ptsunifathi_indonesia/"><i class="fab fa-instagram"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href="https://www.facebook.com/profile.php?id=100093461989142"><i class="fab fa-facebook"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href="https://twitter.com/"><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href="https://www.youtube.com/"><i class="fab fa-youtube"></i></a>';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Get In Touch</h5>';
echo '<p class="mb-2" ><i class="fa fa-map-marker-alt me-3"></i>1JL.Kabul,RT 01 RW 05,';
echo '';
echo '</p>';
echo '';
echo '<p style="margin-left: 30px;" > Desa Peacengaan kulon,';
echo 'Kabupaten Jepara,Jawa Tengah </p>';
echo '<p style="margin-left: 30px;" > Indonesia -59462</p>';
echo '<p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+62 8132 9410041</p>';
echo '<p class="mb-2"><i class="fa fa-envelope me-3"></i>sunifathiindonesia@gmail.com</p>';
echo '';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Quick Links</h5>';
echo '<a class="btn btn-link text-white-50" href="about.php">About Us</a>';
echo '<a class="btn btn-link text-white-50" href="contact.php">Contact Us</a>';
echo '<a class="btn btn-link text-white-50" href="products.php">Our Services</a>';
echo '<a class="btn btn-link text-white-50" href="404.php">Privacy Policy</a>';
echo '<a class="btn btn-link text-white-50" href="404.php">Terms & Condition</a>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Photo Gallery</h5>';
echo '<div class="row g-2 pt-2">';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/1.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/2.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/3.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/4.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/5.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/6.png" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="copyright">';
echo '<div class="row">';
echo '<div class="col-md-6 text-center text-md-start mb-3 mb-md-0">';
echo '&copy; <a   href="#">2023 Suni fathi indonesia </a>, All Right Reserved.';
echo '';
echo '<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you\'d like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->';
echo 'Designed By <a class="border-bottom" target="_blank" href="https://lcmproductions.in/">LCM Productions</a>';
echo '</div>';
echo '<div class="col-md-6 text-center text-md-end">';
echo '<div class="footer-menu">';
echo '<a href="#">Home</a>';
echo '<a href="#">Cookies</a>';
echo '<a href="#">Help</a>';
echo '<a href="#">FQAs</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Footer End -->';
echo '';
echo '';
echo '<!-- Back to Top -->';
echo '<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>';
echo '</div>';
echo '';
echo '<!-- JavaScript Libraries -->';
echo '<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>';
echo '<script src="lib/wow/wow.min.js"></script>';
echo '<script src="lib/easing/easing.min.js"></script>';
echo '<script src="lib/waypoints/waypoints.min.js"></script>';
echo '<script src="lib/owlcarousel/owl.carousel.min.js"></script>';
echo '';
echo '<!-- Template Javascript -->';
echo '<script src="js/main.js"></script>';
echo '<script src="js/translation.js"></script>';
echo '';
echo '<script type="text/javascript">';
echo 'function googleTranslateElementInit() {';
    echo 'new google.translate.TranslateElement({pageLanguage: "en", includedLanguages: "en,fr", layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL}, "google_translate_element");';
    echo '}';
echo '';
echo '';
echo '';
echo '</script>';
echo '</body>';
echo '';
echo '</html>';
?>