<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<title>PT SUNI FATHI INDONESIA</title>';
echo '<meta content="width=device-width, initial-scale=1.0" name="viewport">';
echo '<meta content="" name="keywords">';
echo '<meta content="" name="description">';
echo '';
echo '<!-- Favicon -->';
echo '<link href="img/favicon.ico" rel="icon">';
echo '';
echo '<!-- Google Web Fonts -->';
echo '<link rel="preconnect" href="https://fonts.googleapis.com">';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
echo '<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">';
echo '';
echo '<!-- Icon Font Stylesheet -->';
echo '<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">';
echo '';
echo '<!-- Libraries Stylesheet -->';
echo '<link href="lib/animate/animate.min.css" rel="stylesheet">';
echo '<link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">';
echo '';
echo '<!-- Customized Bootstrap Stylesheet -->';
echo '<link href="css/bootstrap.min.css" rel="stylesheet">';
echo '';
echo '<!-- Template Stylesheet -->';
echo '<link href="css/style.css" rel="stylesheet">';
echo '<link rel="stylesheet" href="css/language.css">';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="container-xxl bg-white p-0">';
echo '<!-- Spinner Start -->';
echo '<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">';
echo '<div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">';
echo '<span class="sr-only">Loading...</span>';
echo '</div>';
echo '</div>';
echo '<!-- Spinner End -->';
echo '';
echo '<div class="video-container " >';
echo '<video autoplay muted loop class="header-video">';
echo '<source src="img/video/x2mate.com-4K UNDER SEA 30 SECONDS DEMO4K HD-(1080p).mp4" type="video/mp4">';
echo '</video>';
echo '<div class="overlay"></div>';
echo '';
echo '<div class="container-fluid nav-bar bg-transparent">';
echo '<nav class="navbar  navbar-expand-lg bg-white navbar-light py-0 px-4" >';
echo '<a href="index.php" class="navbar-brand d-flex align-items-center text-center">';
echo '<div class="logo-container">';
echo '<img class="img-fluid" src="img/logo/sfi logo.png" alt="Icon">';
echo '</div>';
echo '</a>';
echo '<button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarCollapse">';
echo '<div class="navbar-nav ms-auto">';
echo '<a href="index.php" class="nav-item nav-link active">Home</a>';
echo '<a href="about.php" class="nav-item nav-link">About us</a>';
echo '<a href="products.php" class="nav-item nav-link">Products</a>';
echo '';
echo '<a href="contact.php" class="nav-item nav-link">Contact us</a>';
echo '</div>';
echo '';
echo '<div class="trans-section">';
echo '<div id="google_translate_element"></div>';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</nav>';
echo '</div>';
echo '<!-- Navbar End -->';
echo '';
echo '';
echo '<!-- Header Start -->';
echo '<div class="container-fluid header bg-white p-0" style="margin-top: 10px;" >';
echo '<div class="row g-0 align-items-center flex-column-reverse flex-md-row">';
echo '<div class="row g-0 align-items-center">';
echo '<div class="col-md-6 p-5 mt-lg-5">';
echo '<h1 class="display-5 animated fadeIn mt-lg-4 mb-4" style="color: white;">Bringing the <span class="text-primary">Finest Indonesian Fish</span> to the Europe Market</h1>';
echo '<p class="animated fadeIn mb-4 pb-2" style="color: white;">From the pristine waters of Indonesia: Experience the finest fresh seafood delivered to your doorstep in the UK!</p>';
echo '<a href="" class="btn btn-primary py-3 px-5 me-3 animated fadeIn">Get Started</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Header End -->';
echo '';
echo '';
echo '<!-- Header Start -->';
echo '';
echo '<!-- <div class="video-container " >';
echo '<video autoplay muted loop class="header-video">';
echo '<source src="img/video/x2mate.com-4K UNDER SEA 30 SECONDS DEMO4K HD-(1080p).mp4" type="video/mp4">';
echo '</video>';
echo '<div class="overlay"></div>';
echo '<div class="container-fluid nav-bar bg-transparent" >';
echo '<nav class="navbar navbar-expand-lg bg-white navbar-light py-0 px-4">';
echo '<a href="index.php" class="navbar-brand d-flex align-items-center text-center">';
echo '<div class="logo-container">';
echo '<img class="img-fluid" src="img/logo/sfi logo.png" alt="Icon">';
echo '</div>';
echo '</a>';
echo '<button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarCollapse">';
echo '<div class="navbar-nav ms-auto">';
echo '<a href="index.php" class="nav-item nav-link active">Home</a>';
echo '<a href="about.php" class="nav-item nav-link">About us</a>';
echo '<div class="nav-item dropdown">';
echo '<a href="products.php" class="nav-link " data-bs-toggle="dropdown">Products</a>';
echo '';
echo '</div>';
echo '';
echo '<a href="contact.php" class="nav-item nav-link">Contact us</a>';
echo '</div>';
echo '<a href="#" class="btn btn-primary px-3 d-none d-lg-flex">Call</a>';
echo '</div>';
echo '</nav>';
echo '';
echo '<div class="container-fluid header-content" style="padding-top: 350px;" >';
echo '<div class="row g-0 align-items-center">';
echo '<div class="col-md-6 p-5 mt-lg-5">';
echo '<h1 class="display-5 animated fadeIn mt-lg-4 mb-4" style="color: white;">Bringing the <span class="text-primary">Finest Indonesian Fish</span> to the UK Market</h1>';
echo '<p class="animated fadeIn mb-4 pb-2">From the pristine waters of Indonesia: Experience the finest fresh seafood delivered to your doorstep in the UK!</p>';
echo '<a href="" class="btn btn-primary py-3 px-5 me-3 animated fadeIn">Get Started</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div> -->';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<!-- <div class="container-fluid header bg-white p-0">';
echo '<div class="row g-0 align-items-center flex-column-reverse flex-md-row">';
echo '<div class="col-md-6 p-5 mt-lg-5">';
echo '<h1 class="display-5 animated  fadeIn mt-lg-4  mb-4">Bringing the <span class="text-primary">Finest Indonesian Fish</span>   to the UK Market</h1>';
echo '<p class="animated fadeIn mb-4 pb-2">From the pristine waters of Indonesia: Experience the finest fresh seafood delivered to your doorstep in the UK!</p>';
echo '<a href="" class="btn btn-primary py-3 px-5 me-3 animated fadeIn">Get Started</a>';
echo '</div>';
echo '<div class="col-md-6 animated fadeIn">';
echo '<div class="owl-carousel header-carousel"> -->';
echo '<!-- <div class="owl-carousel-item">';
echo '<img class="img-fluid" src="img/header.jpg" alt="">';
echo '</div> -->';
echo '<!-- <div class="owl-carousel-item">';
echo '<img class="img-fluid" src="img/header/indian-mackerel-rastrelliger-kanagurta.jpg" alt="">';
echo '</div>';
echo '<div class="owl-carousel-item">';
echo '<img class="img-fluid" src="img/header/top-view-shrimp-ready-be-cooked.jpg" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div> -->';
echo '<!-- Header End -->';
echo '';
echo '';
echo '<!-- Search Start -->';
echo '<div class="container-fluid bg-primary mb-5 wow fadeIn mt-4" data-wow-delay="0.1s" style="padding: 35px;">';
echo '<div class="container">';
echo '<div class="row g-2">';
echo '<div class="col-md-10">';
echo '<div class="row g-2">';
echo '<div class="col-md-4">';
echo '<div class="card border-0 h-100">';
echo '<div class="card-body">';
echo '<i class="fas fa-medal"></i> Premium Quality Seafood';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4">';
echo '<div class="card border-0 h-100">';
echo '<div class="card-body">';
echo '<i class="fas fa-leaf"></i> Sustainable Sourcing Practices';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4">';
echo '<div class="card border-0 h-100">';
echo '<div class="card-body">';
echo '<i class="fas fa-truck"></i> Reliable and Efficient Delivery';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-md-2">';
echo '<button class="btn btn-dark border-0 w-100 py-3">EXPLORE</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Search End -->';
echo '';
echo '';
echo '<!-- Category Start -->';
echo '<div class="container-xxl py-5">';
echo '<div class="container">';
echo '<div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">';
echo '<h1 class="mb-3">Choose us for responsible Sourcing and Quality</h1>';
echo '<p>We prioritize responsible sourcing and uphold the highest standards of quality. Our commitment to sustainability and excellence sets us apart as your preferred choice for seafood.</p>';
echo '</div>';
echo '<div class="row g-4">';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/category/47446-removebg-preview.png" alt="Icon">';
echo '</div>';
echo '<h6>Sustainability and Traceability</h6>';
echo '<span class="justified-text">Support responsible fishing practices and protect marine ecosystems with our sustainable seafood. </span>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/category/47446__1_-removebg-preview.png" alt="Icon">';
echo '</div>';
echo '<h6>Quality Assurance</h6>';
echo '<span class="justified-text">Rigorous quality control at every stage ensures freshness, taste, and overall product integrity. Impeccable.';
echo '</span>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/category/47446__2_-removebg-preview.png" alt="Icon">';
echo '</div>';
echo '<h6>Customized Packaging and Delivery</h6>';
echo '<span class="justified-text">Tailored bulk packaging solutions for optimal freshness and efficient delivery.</span>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/category/47446__3_-removebg-preview.png" alt="Icon">';
echo '</div>';
echo '<h6>Competitive Pricing and Customer Service</h6>';
echo '<span class="justified-text">Affordable prices and exceptional service to build long-term relationships with our valued customers.</span>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Category End -->';
echo '';
echo '';
echo '<!-- About Start -->';
echo '<div class="container-xxl py-5">';
echo '<div class="container">';
echo '<div class="row g-5 align-items-center">';
echo '<div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">';
echo '<div class="about-img position-relative overflow-hidden p-5 pe-0">';
echo '<img class="img-fluid w-100" src="img/about/20230608100251_[fpdl.in]_blue-container-fish-boat_889227-21413_medium.jpg">';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">';
echo '<h1 class="mb-4">About us</h1>';
echo '';
echo '<h3 class="mb-3">#1 Trusted Frozen fish (sea and land) Source, Fresh & Sustainable</h3>';
echo '<p class="mb-4"> We are an international fish trading company from Indonesia,';
echo 'serving as a full-service partner for fish distribution companies since 2018.';
echo 'Offering a wide range of sea frozen and freshwater fish, sourced from all major production regions in Indonesia,';
echo 'we guarantee quality and reliability. With the ability to ship to any port in the world,';
echo 'we are your go-to choice for efficient and sustainable fish distribution.</p>';
echo '<p><i class="fa fa-check text-primary me-3"></i>Seafood Supplier</p>';
echo '<p><i class="fa fa-check text-primary me-3"></i>Trusted Partner</p>';
echo '<p><i class="fa fa-check text-primary me-3"></i> Customer Satisfaction</p>';
echo '<a class="btn btn-primary py-3 px-5 mt-3" href="about.php">Read More</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- About End -->';
echo '';
echo '';
echo '<!-- Property List Start -->';
echo '<div class="container-xxl py-5">';
echo '<div class="container">';
echo '<div class="row g-0 gx-5 align-items-end ">';
echo '';
echo '<div class="text-center mx-auto mb-5 wow slideInLeft mb-4" data-wow-delay="0.1s">';
echo '<h1 class="mb-3">Our products</h1>';
echo '<p>All our fresh seafood products are';
echo 'freshly catch from Indonesia';
echo 'ocean. To preserve itsfreshness';
echo 'throughout the delivery process, we adopt a special freezing techniqueIQF frozen skill by storing it in a special fibre box contains ice at';
echo 'a controlled temperature of 50C which can last the';
echo 'freshness up to 18 hours.';
echo '</p>';
echo '</div>';
echo '';
echo '<!-- <div class="col-lg-6 text-start text-lg-end wow slideInRight" data-wow-delay="0.1s">';
echo '<ul class="nav nav-pills d-inline-flex justify-content-end mb-5">';
echo '<li class="nav-item me-2">';
echo '<a class="btn btn-outline-primary active" data-bs-toggle="pill" href="#tab-1">Featured</a>';
echo '</li>';
echo '<li class="nav-item me-2">';
echo '<a class="btn btn-outline-primary" data-bs-toggle="pill" href="#tab-2">For Sell</a>';
echo '</li>';
echo '<li class="nav-item me-0">';
echo '<a class="btn btn-outline-primary" data-bs-toggle="pill" href="#tab-3">For Rent</a>';
echo '</li>';
echo '</ul>';
echo '</div> -->';
echo '</div>';
echo '<div class="tab-content">';
echo '<div id="tab-1" class="tab-pane fade show p-0 active">';
echo '<div class="row g-6">';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="property-item rounded overflow-hidden" >';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/home/1.png" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Sell</div>';
echo '<!-- <div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Appartment</div> -->';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">KING FISH</h5>';
echo '<a class="d-block h5 mb-2" href="">Scomberomorus (cavalla)</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>origin : Indonesia</p>';
echo '</div>';
echo '<div class="d-flex m-lg-4 ">';
echo '<small class="flex-fill "><i class="fa fa-cube text-primary " ></i> &nbsp;packing : MC, etc (as per requested)</small>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="property-item rounded overflow-hidden" >';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/home/2.png" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Sell</div>';
echo '<!-- <div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Appartment</div> -->';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">BARRACUDA</h5>';
echo '<a class="d-block h5 mb-2" href="">Ikan Barakuda (Sphyraena barracuda)</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>origin : Indonesia</p>';
echo '</div>';
echo '<div class="d-flex m-lg-4 ">';
echo '<small class="flex-fill "><i class="fa fa-cube text-primary " ></i> &nbsp;packing : MC, etc (as per requested)</small>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="property-item rounded overflow-hidden" >';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/home/3.png" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Sell</div>';
echo '<!-- <div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Appartment</div> -->';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">SILVER POMFRET</h5>';
echo '<a class="d-block h5 mb-2" href="">Ikan Bawal Putih(Pampus argenteus)</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>origin : Indonesia</p>';
echo '</div>';
echo '';
echo '<div class="d-flex m-lg-4 ">';
echo '<small class="flex-fill "><i class="fa fa-cube text-primary " ></i> &nbsp;packing : MC, etc (as per requested)</small>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="property-item rounded overflow-hidden" >';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/home/4.png" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Sell</div>';
echo '<!-- <div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Appartment</div> -->';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">TUNA</h5>';
echo '<a class="d-block h5 mb-2" href="">Ikan Cakalang (Katsuwonus pelamis)</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>origin : Indonesia</p>';
echo '</div>';
echo '<div class="d-flex m-lg-4 ">';
echo '<small class="flex-fill "><i class="fa fa-cube text-primary " ></i> &nbsp;packing : MC, etc (as per requested)</small>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="property-item rounded overflow-hidden" >';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/home/5.png" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Sell</div>';
echo '<!-- <div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Appartment</div> -->';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">FROZEN SQUID</h5>';
echo '<a class="d-block h5 mb-2" href="">Cumi-cumi (Loligo sp)</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>origin : Indonesia</p>';
echo '</div>';
echo '<div class="d-flex m-lg-4 ">';
echo '<small class="flex-fill "><i class="fa fa-cube text-primary " ></i> &nbsp;packing : MC, etc (as per requested)</small>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="property-item rounded overflow-hidden" >';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/home/6.png" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Sell</div>';
echo '<!-- <div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Appartment</div> -->';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">CUTTLE FISH</h5>';
echo '<a class="d-block h5 mb-2" href="">Cuttlefish (Sepiida)</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>origin : Indonesia</p>';
echo '</div>';
echo '<div class="d-flex m-lg-4 ">';
echo '<small class="flex-fill "><i class="fa fa-cube text-primary " ></i> &nbsp;packing : MC, etc (as per requested)</small>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="property-item rounded overflow-hidden" >';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/home/7.png" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Sell</div>';
echo '<!-- <div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Appartment</div> -->';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">RED SNAPPER</h5>';
echo '<a class="d-block h5 mb-2" href="">Ikan Kakap Merah (Lutjanus malabarikus)</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>origin : Indonesia</p>';
echo '</div>';
echo '<div class="d-flex m-lg-4 ">';
echo '<small class="flex-fill "><i class="fa fa-cube text-primary " ></i> &nbsp;packing : MC, etc (as per requested)</small>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="property-item rounded overflow-hidden" >';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/home/8.png" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Sell</div>';
echo '<!-- <div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Appartment</div> -->';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">ARK COCKLE SHELL</h5>';
echo '<a class="d-block h5 mb-2" href="">Kerang bulu (Anadara antiquata)</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>origin : Indonesia</p>';
echo '</div>';
echo '<div class="d-flex m-lg-4 ">';
echo '<small class="flex-fill "><i class="fa fa-cube text-primary " ></i> &nbsp;packing : MC, etc (as per requested)</small>';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<div class="col-12 text-center">';
echo '<a class="btn btn-primary py-3 px-5" href="products.php">Browse More Products</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<!-- <div id="tab-3" class="tab-pane fade show p-0">';
echo '<div class="row g-4">';
echo '<div class="col-lg-4 col-md-6">';
echo '<div class="property-item rounded overflow-hidden">';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/property-1.jpg" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Sell</div>';
echo '<div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Appartment</div>';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">$12,345</h5>';
echo '<a class="d-block h5 mb-2" href="">Golden Urban House For Sell</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>123 Street, New York, USA</p>';
echo '</div>';
echo '<div class="d-flex border-top">';
echo '<small class="flex-fill text-center border-end py-2"><i class="fa fa-ruler-combined text-primary me-2"></i>1000 Sqft</small>';
echo '<small class="flex-fill text-center border-end py-2"><i class="fa fa-bed text-primary me-2"></i>3 Bed</small>';
echo '<small class="flex-fill text-center py-2"><i class="fa fa-bath text-primary me-2"></i>2 Bath</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6">';
echo '<div class="property-item rounded overflow-hidden">';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/property-2.jpg" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Rent</div>';
echo '<div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Villa</div>';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">$12,345</h5>';
echo '<a class="d-block h5 mb-2" href="">Golden Urban House For Sell</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>123 Street, New York, USA</p>';
echo '</div>';
echo '<div class="d-flex border-top">';
echo '<small class="flex-fill text-center border-end py-2"><i class="fa fa-ruler-combined text-primary me-2"></i>1000 Sqft</small>';
echo '<small class="flex-fill text-center border-end py-2"><i class="fa fa-bed text-primary me-2"></i>3 Bed</small>';
echo '<small class="flex-fill text-center py-2"><i class="fa fa-bath text-primary me-2"></i>2 Bath</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6">';
echo '<div class="property-item rounded overflow-hidden">';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/property-3.jpg" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Sell</div>';
echo '<div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Office</div>';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">$12,345</h5>';
echo '<a class="d-block h5 mb-2" href="">Golden Urban House For Sell</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>123 Street, New York, USA</p>';
echo '</div>';
echo '<div class="d-flex border-top">';
echo '<small class="flex-fill text-center border-end py-2"><i class="fa fa-ruler-combined text-primary me-2"></i>1000 Sqft</small>';
echo '<small class="flex-fill text-center border-end py-2"><i class="fa fa-bed text-primary me-2"></i>3 Bed</small>';
echo '<small class="flex-fill text-center py-2"><i class="fa fa-bath text-primary me-2"></i>2 Bath</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6">';
echo '<div class="property-item rounded overflow-hidden">';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/property-4.jpg" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Rent</div>';
echo '<div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Building</div>';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">$12,345</h5>';
echo '<a class="d-block h5 mb-2" href="">Golden Urban House For Sell</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>123 Street, New York, USA</p>';
echo '</div>';
echo '<div class="d-flex border-top">';
echo '<small class="flex-fill text-center border-end py-2"><i class="fa fa-ruler-combined text-primary me-2"></i>1000 Sqft</small>';
echo '<small class="flex-fill text-center border-end py-2"><i class="fa fa-bed text-primary me-2"></i>3 Bed</small>';
echo '<small class="flex-fill text-center py-2"><i class="fa fa-bath text-primary me-2"></i>2 Bath</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6">';
echo '<div class="property-item rounded overflow-hidden">';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/property-5.jpg" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Sell</div>';
echo '<div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Home</div>';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">$12,345</h5>';
echo '<a class="d-block h5 mb-2" href="">Golden Urban House For Sell</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>123 Street, New York, USA</p>';
echo '</div>';
echo '<div class="d-flex border-top">';
echo '<small class="flex-fill text-center border-end py-2"><i class="fa fa-ruler-combined text-primary me-2"></i>1000 Sqft</small>';
echo '<small class="flex-fill text-center border-end py-2"><i class="fa fa-bed text-primary me-2"></i>3 Bed</small>';
echo '<small class="flex-fill text-center py-2"><i class="fa fa-bath text-primary me-2"></i>2 Bath</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-md-6">';
echo '<div class="property-item rounded overflow-hidden">';
echo '<div class="position-relative overflow-hidden">';
echo '<a href=""><img class="img-fluid" src="img/property-6.jpg" alt=""></a>';
echo '<div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">For Rent</div>';
echo '<div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">Shop</div>';
echo '</div>';
echo '<div class="p-4 pb-0">';
echo '<h5 class="text-primary mb-3">$12,345</h5>';
echo '<a class="d-block h5 mb-2" href="">Golden Urban House For Sell</a>';
echo '<p><i class="fa fa-map-marker-alt text-primary me-2"></i>123 Street, New York, USA</p>';
echo '</div>';
echo '<div class="d-flex border-top">';
echo '<small class="flex-fill text-center border-end py-2"><i class="fa fa-ruler-combined text-primary me-2"></i>1000 Sqft</small>';
echo '<small class="flex-fill text-center border-end py-2"><i class="fa fa-bed text-primary me-2"></i>3 Bed</small>';
echo '<small class="flex-fill text-center py-2"><i class="fa fa-bath text-primary me-2"></i>2 Bath</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-12 text-center">';
echo '<a class="btn btn-primary py-3 px-5" href="">Browse More Property</a>';
echo '</div>';
echo '</div>';
echo '</div> -->';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Property List End -->';
echo '';
echo '';
echo '<!-- Call to Action Start -->';
echo '<!-- <div class="container-xxl py-5">';
echo '<div class="container">';
echo '<div class="bg-light rounded p-3">';
echo '<div class="bg-white rounded p-4" style="border: 1px dashed rgba(0, 185, 142, .3)">';
echo '<div class="row g-5 align-items-center">';
echo '<div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">';
echo '<img class="img-fluid rounded w-100" src="img/call-to-action.jpg" alt="">';
echo '</div>';
echo '<div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">';
echo '<div class="mb-4">';
echo '<h1 class="mb-3">Contact With Our Certified Agent</h1>';
echo '<p>Eirmod sed ipsum dolor sit rebum magna erat. Tempor lorem kasd vero ipsum sit sit diam justo sed vero dolor duo.</p>';
echo '</div>';
echo '<a href="" class="btn btn-primary py-3 px-4 me-2"><i class="fa fa-phone-alt me-2"></i>Make A Call</a>';
echo '<a href="" class="btn btn-dark py-3 px-4"><i class="fa fa-calendar-alt me-2"></i>Get Appoinment</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div> -->';
echo '<!-- Call to Action End -->';
echo '';
echo '';
echo '<!-- Team Start -->';
echo '<!-- <div class="container-xxl py-5">';
echo '<div class="container">';
echo '<div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">';
echo '<h1 class="mb-3">Property Agents</h1>';
echo '<p>Eirmod sed ipsum dolor sit rebum labore magna erat. Tempor ut dolore lorem kasd vero ipsum sit eirmod sit. Ipsum diam justo sed rebum vero dolor duo.</p>';
echo '</div>';
echo '<div class="row g-4">';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="team-item rounded overflow-hidden">';
echo '<div class="position-relative">';
echo '<img class="img-fluid" src="img/team-1.jpg" alt="">';
echo '<div class="position-absolute start-50 top-100 translate-middle d-flex align-items-center">';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-facebook-f"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-instagram"></i></a>';
echo '</div>';
echo '</div>';
echo '<div class="text-center p-4 mt-3">';
echo '<h5 class="fw-bold mb-0">Full Name</h5>';
echo '<small>Designation</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.3s">';
echo '<div class="team-item rounded overflow-hidden">';
echo '<div class="position-relative">';
echo '<img class="img-fluid" src="img/team-2.jpg" alt="">';
echo '<div class="position-absolute start-50 top-100 translate-middle d-flex align-items-center">';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-facebook-f"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-instagram"></i></a>';
echo '</div>';
echo '</div>';
echo '<div class="text-center p-4 mt-3">';
echo '<h5 class="fw-bold mb-0">Full Name</h5>';
echo '<small>Designation</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.5s">';
echo '<div class="team-item rounded overflow-hidden">';
echo '<div class="position-relative">';
echo '<img class="img-fluid" src="img/team-3.jpg" alt="">';
echo '<div class="position-absolute start-50 top-100 translate-middle d-flex align-items-center">';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-facebook-f"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-instagram"></i></a>';
echo '</div>';
echo '</div>';
echo '<div class="text-center p-4 mt-3">';
echo '<h5 class="fw-bold mb-0">Full Name</h5>';
echo '<small>Designation</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.7s">';
echo '<div class="team-item rounded overflow-hidden">';
echo '<div class="position-relative">';
echo '<img class="img-fluid" src="img/team-4.jpg" alt="">';
echo '<div class="position-absolute start-50 top-100 translate-middle d-flex align-items-center">';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-facebook-f"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-square mx-1" href=""><i class="fab fa-instagram"></i></a>';
echo '</div>';
echo '</div>';
echo '<div class="text-center p-4 mt-3">';
echo '<h5 class="fw-bold mb-0">Full Name</h5>';
echo '<small>Designation</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div> -->';
echo '<!-- Team End -->';
echo '';
echo '';
echo '<!-- Testimonial Start -->';
echo '<!-- <div class="container-xxl py-5">';
echo '<div class="container">';
echo '<div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">';
echo '<h1 class="mb-3">Our Clients Say!</h1>';
echo '<p>Eirmod sed ipsum dolor sit rebum labore magna erat. Tempor ut dolore lorem kasd vero ipsum sit eirmod sit. Ipsum diam justo sed rebum vero dolor duo.</p>';
echo '</div>';
echo '<div class="owl-carousel testimonial-carousel wow fadeInUp" data-wow-delay="0.1s">';
echo '<div class="testimonial-item bg-light rounded p-3">';
echo '<div class="bg-white border rounded p-4">';
echo '<p>Tempor stet labore dolor clita stet diam amet ipsum dolor duo ipsum rebum stet dolor amet diam stet. Est stet ea lorem amet est kasd kasd erat eos</p>';
echo '<div class="d-flex align-items-center">';
echo '<img class="img-fluid flex-shrink-0 rounded" src="img/testimonial-1.jpg" style="width: 45px; height: 45px;">';
echo '<div class="ps-3">';
echo '<h6 class="fw-bold mb-1">Client Name</h6>';
echo '<small>Profession</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="testimonial-item bg-light rounded p-3">';
echo '<div class="bg-white border rounded p-4">';
echo '<p>Tempor stet labore dolor clita stet diam amet ipsum dolor duo ipsum rebum stet dolor amet diam stet. Est stet ea lorem amet est kasd kasd erat eos</p>';
echo '<div class="d-flex align-items-center">';
echo '<img class="img-fluid flex-shrink-0 rounded" src="img/testimonial-2.jpg" style="width: 45px; height: 45px;">';
echo '<div class="ps-3">';
echo '<h6 class="fw-bold mb-1">Client Name</h6>';
echo '<small>Profession</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="testimonial-item bg-light rounded p-3">';
echo '<div class="bg-white border rounded p-4">';
echo '<p>Tempor stet labore dolor clita stet diam amet ipsum dolor duo ipsum rebum stet dolor amet diam stet. Est stet ea lorem amet est kasd kasd erat eos</p>';
echo '<div class="d-flex align-items-center">';
echo '<img class="img-fluid flex-shrink-0 rounded" src="img/testimonial-3.jpg" style="width: 45px; height: 45px;">';
echo '<div class="ps-3">';
echo '<h6 class="fw-bold mb-1">Client Name</h6>';
echo '<small>Profession</small>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div> -->';
echo '<!-- Testimonial End -->';
echo '';
echo '';
echo '<!-- Footer Start -->';
echo '<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">';
echo '<div class="container py-5">';
echo '<div class="row footer g-5">';
echo '<div class="col-lg-3 col-md-6 ">';
echo '<div class="icon  mb-3">';
echo '<img class="img-fluid " src="img/logo/sfi logo.png" alt="Icon">';
echo '</div>';
echo '<div class="d-flex" style="padding-left: 60px;">';
echo '';
echo '<a class="btn btn-outline-light btn-social" href="https://www.instagram.com/ptsunifathi_indonesia/"><i class="fab fa-instagram"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href="https://www.facebook.com/profile.php?id=100093461989142"><i class="fab fa-facebook"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href="https://twitter.com/"><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href="https://www.youtube.com/"><i class="fab fa-youtube"></i></a>';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Get In Touch</h5>';
echo '<p class="mb-2" ><i class="fa fa-map-marker-alt me-3"></i>1JL.Kabul,RT 01 RW 05,';
echo '';
echo '</p>';
echo '';
echo '<p style="margin-left: 30px;" > Desa Peacengaan kulon,';
echo 'Kabupaten Jepara,Jawa Tengah </p>';
echo '<p style="margin-left: 30px;" > Indonesia -59462</p>';
echo '<p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+62 8132 9410041</p>';
echo '<p class="mb-2"><i class="fa fa-envelope me-3"></i>sunifathiindonesia@gmail.com</p>';
echo '';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Quick Links</h5>';
echo '<a class="btn btn-link text-white-50" href="about.php">About Us</a>';
echo '<a class="btn btn-link text-white-50" href="contact.php">Contact Us</a>';
echo '<a class="btn btn-link text-white-50" href="products.php">Our Services</a>';
echo '<a class="btn btn-link text-white-50" href="404.php">Privacy Policy</a>';
echo '<a class="btn btn-link text-white-50" href="404.php">Terms & Condition</a>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Photo Gallery</h5>';
echo '<div class="row g-2 pt-2">';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/1.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/2.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/3.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/4.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/5.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/6.png" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="copyright">';
echo '<div class="row">';
echo '<div class="col-md-6 text-center text-md-start mb-3 mb-md-0">';
echo '&copy; <a   href="#">2023 Suni fathi indonesia </a>, All Right Reserved.';
echo '';
echo '<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you\'d like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->';
echo 'Designed By <a class="border-bottom" target="_blank" href="https://lcmproductions.in/">LCM Productions</a>';
echo '</div>';
echo '<div class="col-md-6 text-center text-md-end">';
echo '<div class="footer-menu">';
echo '<a href="#">Home</a>';
echo '<a href="#">Cookies</a>';
echo '<a href="#">Help</a>';
echo '<a href="#">FQAs</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Footer End -->';
echo '';
echo '';
echo '<!-- Back to Top -->';
echo '<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>';
echo '</div>';
echo '';
echo '<!-- JavaScript Libraries -->';
echo '<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>';
echo '<script src="lib/wow/wow.min.js"></script>';
echo '<script src="lib/easing/easing.min.js"></script>';
echo '<script src="lib/waypoints/waypoints.min.js"></script>';
echo '<script src="lib/owlcarousel/owl.carousel.min.js"></script>';
echo '';
echo '<!-- Template Javascript -->';
echo '<script src="js/main.js"></script>';
echo '';
echo '<script src="js/translation.js"></script>';
echo '';
echo '<script type="text/javascript">';
echo 'function googleTranslateElementInit() {';
echo 'new google.translate.TranslateElement({pageLanguage: "en", includedLanguages: "en,fr", layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL}, "google_translate_element");';
echo '}';
echo '';
echo '';
echo '';
echo '</script>';
echo '</body>';
echo '';
echo '</html>';
?>