<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<title>Makaan - Real Estate HTML Template</title>';
echo '<meta content="width=device-width, initial-scale=1.0" name="viewport">';
echo '<meta content="" name="keywords">';
echo '<meta content="" name="description">';
echo '';
echo '<!-- Favicon -->';
echo '<link href="img/favicon.ico" rel="icon">';
echo '';
echo '<!-- Google Web Fonts -->';
echo '<link rel="preconnect" href="https://fonts.googleapis.com">';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
echo '<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">';
echo '';
echo '<!-- Icon Font Stylesheet -->';
echo '<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">';
echo '<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">';
echo '';
echo '<!-- Libraries Stylesheet -->';
echo '<link href="lib/animate/animate.min.css" rel="stylesheet">';
echo '<link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">';
echo '';
echo '<!-- Customized Bootstrap Stylesheet -->';
echo '<link href="css/bootstrap.min.css" rel="stylesheet">';
echo '<link rel="stylesheet" href="css/language.css">';
echo '<!-- Template Stylesheet -->';
echo '<link href="css/style.css" rel="stylesheet">';
echo '</head>';
echo '';
echo '<body>';
echo '<div class="container-xxl bg-white p-0">';
echo '<!-- Spinner Start -->';
echo '<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">';
echo '<div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">';
echo '<span class="sr-only">Loading...</span>';
echo '</div>';
echo '</div>';
echo '<!-- Spinner End -->';
echo '';
echo '';
echo '<!-- Navbar Start -->';
echo '<div class="container-fluid nav-bar bg-transparent">';
echo '<nav class="navbar  navbar-expand-lg bg-white navbar-light py-0 px-4" >';
echo '<a href="index.php" class="navbar-brand d-flex align-items-center text-center">';
echo '<div class="logo-container">';
echo '<img class="img-fluid" src="img/logo/sfi logo.png" alt="Icon">';
echo '</div>';
echo '</a>';
echo '<button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarCollapse">';
echo '<div class="navbar-nav ms-auto">';
echo '<a href="index.php" class="nav-item nav-link active">Home</a>';
echo '<a href="about.php" class="nav-item nav-link">About us</a>';
echo '<div class="nav-item dropdown">';
echo '<a href="products.php" class="nav-link " data-bs-toggle="dropdown">Products</a>';
echo '';
echo '</div>';
echo '';
echo '<a href="contact.php" class="nav-item nav-link">Contact us</a>';
echo '</div>';
echo '<div class="trans-section">';
echo '<div id="google_translate_element"></div>';
echo '';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '</div>';
echo '<!-- Navbar End -->';
echo '';
echo '';
echo '<!-- Header Start -->';
echo '<div class="container-fluid header bg-white p-0">';
echo '<div class="row g-0 align-items-center flex-column-reverse flex-md-row">';
echo '<div class="col-md-6 p-5 mt-lg-5">';
echo '<h1 class="display-5 animated fadeIn mb-4">Products</h1>';
echo '<nav aria-label="breadcrumb animated fadeIn">';
echo '<ol class="breadcrumb text-uppercase">';
echo '<li class="breadcrumb-item"><a href="index.php">Home</a></li>';
echo '';
echo '<li class="breadcrumb-item text-body active" aria-current="page">Products</li>';
echo '</ol>';
echo '</nav>';
echo '</div>';
echo '<div class="col-md-6 animated fadeIn">';
echo '<img class="img-fluid" src="img/header/indian-mackerel-rastrelliger-kanagurta.jpg" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Header End -->';
echo '';
echo '';
echo '<!-- Search Start -->';
echo '<div class="container-fluid bg-primary mb-5 wow fadeIn mt-4" data-wow-delay="0.1s" style="padding: 35px;">';
echo '<div class="container">';
echo '<div class="row g-2">';
echo '<div class="col-md-10">';
echo '<div class="row g-2">';
echo '<div class="col-md-4">';
echo '<div class="card border-0 h-100">';
echo '<div class="card-body">';
echo '<i class="fas fa-medal"></i> Premium Quality Seafood';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4">';
echo '<div class="card border-0 h-100">';
echo '<div class="card-body">';
echo '<i class="fas fa-leaf"></i> Sustainable Sourcing Practices';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-md-4">';
echo '<div class="card border-0 h-100">';
echo '<div class="card-body">';
echo '<i class="fas fa-truck"></i> Reliable and Efficient Delivery';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="col-md-2">';
echo '<button class="btn btn-dark border-0 w-100 py-3">EXPLORE</button>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Search End -->';
echo '';
echo '';
echo '<!-- Category Start -->';
echo '<div class="container-xxl py-5">';
echo '<div class="container">';
echo '<div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">';
echo '<h1 class="mb-3">Our products</h1>';
echo '<p>All our fresh seafood products are';
echo 'freshly catch from Indonesia';
echo 'ocean. To preserve itsfreshness';
echo 'throughout the delivery process, we adopt a special freezing techniqueIQF frozen skill by storing it in a special fibre box contains ice at';
echo 'a controlled temperature of 50C which can last the';
echo 'freshness up to 18 hours. Other than that, we use CPF,';
echo 'that use an automatic plate freezer for freezing food';
echo 'products in boxes or trays, or in containers of low mechanical strength and therefore being deformable, or';
echo 'of nonparallelepiped shape.</p>';
echo '</div>';
echo '<div class="row g-4">';
echo '';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/1.jpg" alt="Icon">';
echo '</div>';
echo '<h6>SILVER POMFRET</h6>';
echo '<span style="font-size: 14px;">Ikan Bawal Putih (Pampus argenteus)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/2.jpg" alt="Icon">';
echo '</div>';
echo '<h6>GOURAMI</h6>';
echo '<span style="font-size: 14px;">Ikan Gurame (Osphronemus goramy)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/3.jpg" alt="Icon">';
echo '</div>';
echo '<h6>NILA TILAPIA</h6>';
echo '<span style="font-size: 14px;">Ikan Nila (Oreochromis niloticus)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<!-- <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/4.jpg" alt="Icon">';
echo '</div>';
echo '<h6>INDO PACIFIC MACKEREL</h6>';
echo '<span style="font-size: 14px;">Ikan Kembung Layar (Rastrelliger sp)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div> -->';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/5.jpg" alt="Icon">';
echo '</div>';
echo '<h6>INDO PACIFIC MACKEREL</h6>';
echo '<span style="font-size: 14px;">Ikan Kembung Banjar (Rastrelliger sp)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/6.jpg" alt="Icon">';
echo '</div>';
echo '<h6>BALI SARDINELLA</h6>';
echo '<span style="font-size: 14px;">Ikan Lemuru (Sardinella lemuru)  </span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/7.jpg" alt="Icon">';
echo '</div>';
echo '<h6>SARDINES</h6>';
echo '<span style="font-size: 14px;">Ikan Sarden (Sardina pilchardus)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/8.jpg" alt="Icon">';
echo '</div>';
echo '<h6>BLACK POMFRET</h6>';
echo '<span style="font-size: 14px;">Ikan Bawal Hitam (Fermio niger)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/9.jpg" alt="Icon">';
echo '</div>';
echo '<h6>GOLDBANDED FUSILIER</h6>';
echo '<span style="font-size: 14px;">Ikan Pisang Pisang (Pterocaesio chrysozona)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/10.jpg" alt="Icon">';
echo '</div>';
echo '<h6>YELLOWSTRIPE TREVALLY</h6>';
echo '<span style="font-size: 14px;">Ikan Pisang pisang (Selaroides leptolepsis)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/11.jpg" alt="Icon">';
echo '</div>';
echo '<h6>GIANT THREADFISH</h6>';
echo '<span style="font-size: 14px;">Ikan Kuro (Eleutheronema tetradactylum)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/12.jpg" alt="Icon">';
echo '</div>';
echo '<h6>BIGEYE SCAD</h6>';
echo '<span style="font-size: 14px;">Ikan Bentrong (Selar crumenophthalmus)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/13.jpg" alt="Icon">';
echo '</div>';
echo '<h6>LEOPARD CORAL TROUT</h6>';
echo '<span style="font-size: 14px;">Ikan Kerapu Lodi (Plectropomus sp)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/14.jpg" alt="Icon">';
echo '</div>';
echo '<h6>BARRED CHEEK CORAL TROUT</h6>';
echo '<span style="font-size: 14px;">Ikan Kerapu Sunu (Plectropomus leopardus)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/15.jpg" alt="Icon">';
echo '</div>';
echo '<h6>SALMON</h6>';
echo '<span style="font-size: 14px;">Ikan Salmon (Oncorhynchus sp)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/16.jpg" alt="Icon">';
echo '</div>';
echo '<h6>YELLOW PIKE-CONGER</h6>';
echo '<span style="font-size: 14px;">Ikan Cunang (Congresox talabon)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/17.jpg" alt="Icon">';
echo '</div>';
echo '<h6>SPANISH MACKEREL</h6>';
echo '<span style="font-size: 14px;">Ikan Tenggiri (Scomberomorus commersoni)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/18.jpg" alt="Icon">';
echo '</div>';
echo '<h6>HAIRTAIL</h6>';
echo '<span style="font-size: 14px;">Ikan Layur (Trichirius lepturus)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/19.jpg" alt="Icon">';
echo '</div>';
echo '<h6>DORY FISH</h6>';
echo '<span style="font-size: 14px;">Ikan Patin (Pangasius pangasius)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/20.jpg" alt="Icon">';
echo '</div>';
echo '<h6>CROAKER</h6>';
echo '<span style="font-size: 14px;">Gulamah (Nibea soldado)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/21.jpg" alt="Icon">';
echo '</div>';
echo '<h6>SMALL THOOTED EMPERUR</h6>';
echo '<span style="font-size: 14px;">Ikan Lencam (Lethrinus sp)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/22.jpg" alt="Icon">';
echo '</div>';
echo '<h6>RED SNAPPER</h6>';
echo '<span style="font-size: 14px;">Ikan Kakap Merah (Lutjanus malabarikus)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/23.jpg" alt="Icon">';
echo '</div>';
echo '<h6>BARRAMUNDI BREAMS</h6>';
echo '<span style="font-size: 14px;">Ikan Kakap Putiih (Lates calcarifer)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/24.jpg" alt="Icon">';
echo '</div>';
echo '<h6>YELLOWTAIL FISH</h6>';
echo '<span style="font-size: 14px;">Ikan Ekor Kuning (Seriola lalandi)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/25.jpg" alt="Icon">';
echo '</div>';
echo '<h6>PARROT FISH </h6>';
echo '<span style="font-size: 14px;">Ikan Kakatua ( Scaridae)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/26.jpg" alt="Icon">';
echo '</div>';
echo '<h6>SKIPJACK TUNA</h6>';
echo '<span style="font-size: 14px;">Ikan Cakalang (Katsuwonus pelamis)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/27.jpg" alt="Icon">';
echo '</div>';
echo '<h6>MAHI MAHI FISH</h6>';
echo '<span style="font-size: 14px;">Ikan Lemadang (Coryphaena hippurus)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/28.jpg" alt="Icon">';
echo '</div>';
echo '<h6>RABBIT FISH</h6>';
echo '<span style="font-size: 14px;">Ikan Baronang (Siganus sp)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/29.jpg" alt="Icon">';
echo '</div>';
echo '<h6>GOLDEN JACK</h6>';
echo '<span style="font-size: 14px;">Ikan Kuwe (Charanx sp)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/anchovi.png" alt="Icon">';
echo '</div>';
echo '<h6>ANCHOVIES</h6>';
echo '<span style="font-size: 14px;">Ikan Teri (Stolepthorus sp)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/31.jpg" alt="Icon">';
echo '</div>';
echo '<h6>BARRACUDA</h6>';
echo '<span style="font-size: 14px;">Ikan Barakuda (Sphyraena barracuda)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/32.jpg" alt="Icon">';
echo '</div>';
echo '<h6>DEEP LEATHERSKI</h6>';
echo '<span style="font-size: 14px;">Ikan Talang-talang (Chorinemus tala)                                </span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/33.jpg" alt="Icon">';
echo '</div>';
echo '<h6>MARINE CATFISH</h6>';
echo '<span style="font-size: 14px;">Ikan Manyung (Tachiurus cordyla)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/34.jpg" alt="Icon">';
echo '</div>';
echo '<h6>EASTER LITTLE TUNAS</h6>';
echo '<span style="font-size: 14px;">Ikan Tongkol (Euthinnus sp)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/35.jpg" alt="Icon">';
echo '</div>';
echo '<h6>CHUB MACKEREL</h6>';
echo '<span style="font-size: 14px;">Ikan Salem (Scomber japonicus)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/36.jpg" alt="Icon">';
echo '</div>';
echo '<h6>FROZEN SQUID</h6>';
echo '<span style="font-size: 14px;">Cumi-cumi (Loligo sp)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<!-- <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/37.jpg" alt="Icon">';
echo '</div>';
echo '<h6>FROZEN SQUID</h6>';
echo '<span style="font-size: 14px;">Cumi-cumi (Loligo sp)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div> -->';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/38.jpg" alt="Icon">';
echo '</div>';
echo '<h6>CUTTLE FISH</h6>';
echo '<span style="font-size: 14px;">Sotong (Sepia sp)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/39.jpg" alt="Icon">';
echo '</div>';
echo '<h6>ARK COCKLE SHELL</h6>';
echo '<span style="font-size: 14px;">Kerang bulu (Anadara antiquata)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/prawn.png" alt="Icon">';
echo '</div>';
echo '<h6>SHRIMP</h6>';
echo '<span style="font-size: 14px;">Udang (Panaeus sp)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';


echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/41.jpg" alt="Icon">';
echo '</div>';
echo '<h6>CHOMMEND WHINDOW SHELL</h6>';
echo '<span style="font-size: 14px;">Kerang Simping (Placuna placenta)</span>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
echo '<div class="rounded p-4">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid" src="img/PRODUCTS/42.jpg" alt="Icon">';
echo '</div>';
echo '<h6>BABY CALM</h6>';
echo '<div class="p-icon" style="font-size: 14px;">';
echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
// Establish a database connection
$hostname = '';  // Replace 'your_host' with the actual hostname or IP address
$username = 'sfidatabase';
$password = 'brNa7NrRh1__UA0V';
$database = 'sfi_db';

$conn = new mysqli($hostname, $username, $password, $database);
if ($conn->connect_error) {
  die("Connection failed: " . $conn->connect_error);
}

// Retrieve the fish records from the "products" table
$sql = "SELECT * FROM products";
$result = $conn->query($sql);

// Display the fish names and images
if ($result->num_rows > 0) {
  while ($row = $result->fetch_assoc()) {
    $fishName = $row['name'];
    $fishImage = $row['image'];
   

    echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
    echo '<a class="cat-item d-block bg-light text-center rounded p-3" href="">';
    echo '<div class="rounded p-4">';
    echo '<div class="icon mb-3">';
    echo '<img class="img-fluid" src="' . $fishImage . '" alt="Icon">';
    echo '</div>';
    echo '<h6>' . $fishName . '</h6>';
    echo '<div class="p-icon" style="font-size: 14px;">';
    echo '<p ><i class="fas fa-map-marker-alt"></i> &nbsp; origin : Indonesia </p>';
    echo '<p ><i class="fas fa-suitcase"></i> &nbsp; packing : MC, etc (as per requested) </p>';
    echo '</div>';
    echo '</div>';
    echo '</a>';
    echo '</div>';
  }
} else {
  echo "No fish found.";
}

$conn->close();





echo '<div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">';
echo '</div>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Category End -->';
echo '';
echo '';
echo '<!-- Footer Start -->';
echo '<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">';
echo '<div class="container py-5">';
echo '<div class="row g-5">';
echo '<div class="col-lg-3 col-md-6 ">';
echo '<div class="icon mb-3">';
echo '<img class="img-fluid " src="img/logo/sfi logo.png" alt="Icon">';
echo '</div>';
echo '<div class="d-flex" style="padding-left: 60px;">';
echo '';
echo '<a class="btn btn-outline-light btn-social" href="https://www.instagram.com/ptsunifathi_indonesia/"><i class="fab fa-instagram"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href="https://www.facebook.com/profile.php?id=100093461989142"><i class="fab fa-facebook"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href="https://twitter.com/"><i class="fab fa-twitter"></i></a>';
echo '<a class="btn btn-outline-light btn-social" href="https://www.youtube.com/"><i class="fab fa-youtube"></i></a>';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Get In Touch</h5>';
echo '<p class="mb-2" ><i class="fa fa-map-marker-alt me-3"></i>1JL.Kabul,RT 01 RW 05,';
echo '';
echo '</p>';
echo '';
echo '<p style="margin-left: 30px;" > Desa Peacengaan kulon,';
echo 'Kabupaten Jepara,Jawa Tengah </p>';
echo '<p style="margin-left: 30px;" > Indonesia -59462</p>';
echo '<p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+62 8132 9410041</p>';
echo '<p class="mb-2"><i class="fa fa-envelope me-3"></i>sunifathiindonesia@gmail.com</p>';
echo '';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Quick Links</h5>';
echo '<a class="btn btn-link text-white-50" href="about.php">About Us</a>';
echo '<a class="btn btn-link text-white-50" href="contact.php">Contact Us</a>';
echo '<a class="btn btn-link text-white-50" href="products.php">Our Services</a>';
echo '<a class="btn btn-link text-white-50" href="404.php">Privacy Policy</a>';
echo '<a class="btn btn-link text-white-50" href="404.php">Terms & Condition</a>';
echo '</div>';
echo '<div class="col-lg-3 col-md-6">';
echo '<h5 class="text-white mb-4">Photo Gallery</h5>';
echo '<div class="row g-2 pt-2">';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/1.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/2.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/3.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/4.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/5.png" alt="">';
echo '</div>';
echo '<div class="col-4">';
echo '<img class="img-fluid rounded bg-light p-1" src="img/gallery/6.png" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="copyright">';
echo '<div class="row">';
echo '<div class="col-md-6 text-center text-md-start mb-3 mb-md-0">';
echo '&copy; <a   href="#">2023 Suni fathi indonesia </a>, All Right Reserved.';
echo '';
echo '<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you\'d like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->';
echo 'Designed By <a class="border-bottom" target="_blank" href="https://lcmproductions.in/">LCM Productions</a>';
echo '</div>';
echo '<div class="col-md-6 text-center text-md-end">';
echo '<div class="footer-menu">';
echo '<a href="#">Home</a>';
echo '<a href="#">Cookies</a>';
echo '<a href="#">Help</a>';
echo '<a href="#">FQAs</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- Footer End -->';
echo '';
echo '';
echo '<!-- Back to Top -->';
echo '<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>';
echo '</div>';
echo '';
echo '<!-- JavaScript Libraries -->';
echo '<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>';
echo '<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>';
echo '<script src="lib/wow/wow.min.js"></script>';
echo '<script src="lib/easing/easing.min.js"></script>';
echo '<script src="lib/waypoints/waypoints.min.js"></script>';
echo '<script src="lib/owlcarousel/owl.carousel.min.js"></script>';
echo '';
echo '<!-- Template Javascript -->';
echo '<script src="js/main.js"></script>';
echo '<script src="js/translation.js"></script>';
echo '';
echo '<script type="text/javascript">';
echo 'function googleTranslateElementInit() {';
    echo 'new google.translate.TranslateElement({pageLanguage: "en", includedLanguages: "en,fr", layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL}, "google_translate_element");';
    echo '}';
echo '';
echo '';
echo '';
echo '</script>';

echo '</body>';
echo '';
echo '</html>';
?>
